name: Feature Request
description: Share an idea for the modification.
labels: "Feature"
assignees: "northwesttreesgaming"
body:
 - type: textarea
   attributes:
    label: Feature description
    description: Explain clearly what you would like to see in the modification.
    placeholder: Type your message here.
   validations:
    required: true
 - type: textarea
   attributes:
    label: Reason to add it
    description: Provide at least one reason that makes the feature worth adding.
    placeholder: Type your reasons here.
   validations:
    required: true
